apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPCluster
metadata:
  name: {{ .Values.clusterName }}
  namespace: default
spec:
  network:
    name: default
  project: {{ .Values.gcpProject }}
  region: {{ .Values.gcpRegion }}