apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ .Values.clusterName }}-md-0
  namespace: default
spec:
  clusterName: {{ .Values.clusterName}}
  replicas: {{ .Values.workerReplicas }}
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ .Values.clusterName }}-md-0
      clusterName: {{ .Values.clusterName }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: GCPMachineTemplate
        name: {{ .Values.clusterName }}-md-0
      version: {{ .Values.kubernetesVersion }}