apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding-management.yaml
- cluster-role-binding-workload.yaml
- cluster-role-management.yaml
- cluster-role-workload.yaml
- Deployment.yaml
- service-account.yaml
