apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: dev-cluster-autoscaler
  namespace: argocd
spec:
  destination: # This is the cluster where the app will be deployed
    name: in-cluster
    namespace: default
  project: default
  source:
    path: kustomize-cluster-autoscaler/overlays/dev
    repoURL: https://github.com/vfiftyfive/capi-clusters.git
    targetRevision: HEAD 