apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
configurations:
- nameReference.yaml
patches:
- path: deployment.yaml
generators:
- secret-generator.yaml